"""
Step F — DDL generation + LDM assembly

Converts the LDM result dict (from step_ldm_promote.py) into:
  1. SQL DDL — CREATE TABLE statements (ANSI + Snowflake variants)
  2. Mermaid erDiagram — visual LDM with all columns
  3. FR coverage matrix — which table/column satisfies which requirement
  4. Table summary — grain, SCD type, row counts, metric additivity

No LLM calls — fully rule-based from the LDM result structure.
"""

import sys, os, re, json
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))
from agent.ldm_conventions import (
    SCHEMA,
    enforce_ldm_naming,
    enforce_mandatory_fks,
    GRAIN_DECLARATIONS,
    SCD_ASSIGNMENTS,
)

# ── Mermaid-safe name ─────────────────────────────────────────────────────────

def _safe(name: str) -> str:
    return re.sub(r'[^A-Za-z0-9]', '', name)


# ── DDL generator ─────────────────────────────────────────────────────────────

def _ddl_for_table(table: dict, dialect: str = "ansi") -> str:
    """Generate CREATE TABLE DDL for a single table."""
    table_name  = table.get("table_name", "UNKNOWN")
    columns     = table.get("columns", [])
    grain       = table.get("grain", "")
    scd_type    = table.get("scd_type")
    source      = table.get("source_system", "")
    fr_refs     = ", ".join(table.get("fr_references", []))

    lines = [
        f"-- {'─'*73}",
        f"-- {table_name}",
        f"-- Grain: {grain}",
    ]
    if scd_type:
        lines.append(f"-- SCD Type: {scd_type}")
    if source:
        lines.append(f"-- Source: {source}")
    if fr_refs:
        lines.append(f"-- FR refs: {fr_refs}")
    lines.append(f"-- {'─'*73}")

    if dialect == "snowflake":
        lines.append(f"CREATE TABLE IF NOT EXISTS {SCHEMA}.{table_name} (")
    else:
        lines.append(f"CREATE TABLE {SCHEMA}.{table_name} (")

    col_defs = []
    pk_cols  = []
    fk_cols  = []

    for col in columns:
        name      = col.get("name", "COL")
        dtype     = col.get("data_type", "VARCHAR2(100)")
        nullable  = col.get("nullable", True)
        is_pk     = col.get("is_pk", False)
        is_fk     = col.get("is_fk", False)
        desc      = col.get("description", "")

        # Snowflake uses different types
        if dialect == "snowflake":
            dtype = (dtype
                .replace("VARCHAR2", "VARCHAR")
                .replace("NUMBER", "NUMBER")
                .replace("CHAR(1)", "CHAR(1)")
                .replace("TIMESTAMP", "TIMESTAMP_NTZ"))

        null_str  = "NOT NULL" if not nullable else "NULL"
        comment   = f"  -- {desc}" if desc else ""

        col_line = f"    {name:<35} {dtype:<18} {null_str}{comment}"
        col_defs.append(col_line)

        if is_pk:
            pk_cols.append(name)
        if is_fk and col.get("fk_table"):
            fk_cols.append((name, col["fk_table"]))

    lines.append(",\n".join(col_defs))

    # Constraints
    constraints = []
    if pk_cols:
        pk_list = ", ".join(pk_cols)
        constraints.append(f"    CONSTRAINT PK_{table_name} PRIMARY KEY ({pk_list})")

    for fk_col, fk_table in fk_cols:
        constraints.append(
            f"    CONSTRAINT FK_{table_name}_{fk_col} "
            f"FOREIGN KEY ({fk_col}) REFERENCES {SCHEMA}.{fk_table} ({fk_col})"
        )

    if constraints:
        lines[-1] = lines[-1] + ","
        lines.append(",\n".join(constraints))

    lines.append(");")
    lines.append("")

    return "\n".join(lines)


def generate_ddl(ldm_result: dict, dialect: str = "ansi") -> str:
    """Generate complete DDL for all tables in the LDM result."""
    all_tables = (
        ldm_result.get("dimension_tables", []) +
        ldm_result.get("fact_tables", []) +
        ldm_result.get("bridge_tables", []) +
        ldm_result.get("reference_tables", [])
    )

    dialect_label = "Snowflake" if dialect == "snowflake" else "ANSI SQL"
    header = f"""-- {'='*77}
-- LOGICAL DATA MODEL — Merchandising Sales & Profit
-- Dialect: {dialect_label}
-- Schema:  {SCHEMA}
-- Tables:  {len(all_tables)}
-- Generated by DataModelerAgent Step F
-- {'='*77}

CREATE SCHEMA IF NOT EXISTS {SCHEMA};

"""
    sections = {
        "DIMENSION TABLES": ldm_result.get("dimension_tables", []),
        "FACT TABLES":      ldm_result.get("fact_tables", []),
        "BRIDGE TABLES":    ldm_result.get("bridge_tables", []),
        "REFERENCE TABLES": ldm_result.get("reference_tables", []),
    }

    parts = [header]
    for section_name, tables in sections.items():
        if not tables:
            continue
        parts.append(f"-- {'─'*77}")
        parts.append(f"-- {section_name}")
        parts.append(f"-- {'─'*77}\n")
        for t in tables:
            parts.append(_ddl_for_table(t, dialect))

    # Subject area views for FR-018
    parts.append(_generate_views(ldm_result))

    return "\n".join(parts)


def _generate_views(ldm_result: dict) -> str:
    """Generate AS-IS / AS-WAS / PIT views for FR-018."""
    fact_names = [t.get("table_name","") for t in ldm_result.get("fact_tables",[])]
    if "FACT_SALES" not in fact_names:
        return ""

    return """-- ─────────────────────────────────────────────────────────────────────────────
-- SUBJECT AREA VIEWS — FR-018 (As-Is / As-Was / Point-in-Time separation)
-- The BI layer queries ONLY these views, never the physical fact tables.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE OR REPLACE VIEW MERCH_DW.V_SALES_AS_IS AS
SELECT fs.*, p.ITEM_ID, p.ITEM_DESC, p.DEPT_ID, p.DEPT_DESC,
       p.CLASS_ID, p.SUBCLASS_ID, p.DIVISION_ID, p.CURRENT_FLAG AS DIM_CURRENT,
       o.STORE_ID, o.STORE_DESC, o.REGION_ID, o.COMP_STORE_FLAG,
       c.FISCAL_DATE, c.FISCAL_WEEK, c.FISCAL_PERIOD, c.FISCAL_YEAR,
       pt.PRICE_TYPE_CODE, pt.PRICE_TYPE_DESC
FROM   MERCH_DW.FACT_SALES fs
JOIN   MERCH_DW.DIM_PRODUCT           p  ON fs.PRODUCT_KEY   = p.PRODUCT_KEY
                                         AND p.CURRENT_FLAG  = 'Y'
JOIN   MERCH_DW.DIM_ORGANISATION      o  ON fs.ORG_KEY        = o.ORG_KEY
                                         AND o.CURRENT_FLAG  = 'Y'
JOIN   MERCH_DW.DIM_BUSINESS_CALENDAR c  ON fs.DATE_KEY       = c.DATE_KEY
JOIN   MERCH_DW.DIM_RETAIL_PRICE_TYPE pt ON fs.PRICE_TYPE_KEY = pt.PRICE_TYPE_KEY
WHERE  fs.ANALYSIS_MODE_CODE = 'AS_IS';


CREATE OR REPLACE VIEW MERCH_DW.V_SALES_AS_WAS AS
SELECT fs.*, p.ITEM_ID, p.ITEM_DESC, p.DEPT_ID, p.DEPT_DESC,
       p.CLASS_ID, p.SUBCLASS_ID, p.DIVISION_ID,
       o.STORE_ID, o.STORE_DESC, o.REGION_ID, o.COMP_STORE_FLAG,
       c.FISCAL_DATE, c.FISCAL_WEEK, c.FISCAL_PERIOD, c.FISCAL_YEAR,
       pt.PRICE_TYPE_CODE, pt.PRICE_TYPE_DESC
FROM   MERCH_DW.FACT_SALES fs
JOIN   MERCH_DW.DIM_BUSINESS_CALENDAR c  ON fs.DATE_KEY      = c.DATE_KEY
JOIN   MERCH_DW.DIM_PRODUCT           p  ON fs.PRODUCT_KEY   = p.PRODUCT_KEY
                                         AND c.FISCAL_DATE BETWEEN p.EFFECTIVE_DATE AND p.EXPIRY_DATE
JOIN   MERCH_DW.DIM_ORGANISATION      o  ON fs.ORG_KEY        = o.ORG_KEY
                                         AND c.FISCAL_DATE BETWEEN o.EFFECTIVE_DATE AND o.EXPIRY_DATE
JOIN   MERCH_DW.DIM_RETAIL_PRICE_TYPE pt ON fs.PRICE_TYPE_KEY = pt.PRICE_TYPE_KEY
WHERE  fs.ANALYSIS_MODE_CODE = 'AS_WAS';


CREATE OR REPLACE VIEW MERCH_DW.V_SALES_POINT_IN_TIME AS
SELECT fs.*, p.ITEM_ID, p.ITEM_DESC, p.DEPT_ID, p.DEPT_DESC,
       p.CLASS_ID, p.SUBCLASS_ID, p.DIVISION_ID,
       p.EFFECTIVE_DATE AS DIM_EFFECTIVE_DATE,
       o.STORE_ID, o.STORE_DESC, o.REGION_ID, o.COMP_STORE_FLAG,
       c.FISCAL_DATE, c.FISCAL_WEEK, c.FISCAL_PERIOD, c.FISCAL_YEAR,
       pt.PRICE_TYPE_CODE, pt.PRICE_TYPE_DESC
FROM   MERCH_DW.FACT_SALES fs
JOIN   MERCH_DW.DIM_BUSINESS_CALENDAR c  ON fs.DATE_KEY      = c.DATE_KEY
JOIN   MERCH_DW.DIM_PRODUCT           p  ON fs.PRODUCT_KEY   = p.PRODUCT_KEY
                                         -- Replace DATE '2000-01-01' with :PIT_DATE bind var in BI layer
                                         AND DATE '2000-01-01' BETWEEN p.EFFECTIVE_DATE AND p.EXPIRY_DATE
JOIN   MERCH_DW.DIM_ORGANISATION      o  ON fs.ORG_KEY        = o.ORG_KEY
                                         AND DATE '2000-01-01' BETWEEN o.EFFECTIVE_DATE AND o.EXPIRY_DATE
JOIN   MERCH_DW.DIM_RETAIL_PRICE_TYPE pt ON fs.PRICE_TYPE_KEY = pt.PRICE_TYPE_KEY
WHERE  fs.ANALYSIS_MODE_CODE = 'POINT_IN_TIME';

-- Same pattern for FACT_MARKDOWN:
-- V_MARKDOWN_AS_IS, V_MARKDOWN_AS_WAS, V_MARKDOWN_POINT_IN_TIME

"""


# ── Mermaid erDiagram ─────────────────────────────────────────────────────────

def generate_mermaid(ldm_result: dict) -> str:
    """Generate Mermaid erDiagram with all tables and columns."""
    lines = ["erDiagram"]

    all_tables = (
        ldm_result.get("dimension_tables", []) +
        ldm_result.get("fact_tables", []) +
        ldm_result.get("bridge_tables", []) +
        ldm_result.get("reference_tables", [])
    )

    # Entity definitions
    for table in all_tables:
        name = _safe(table.get("table_name",""))
        if not name:
            continue
        lines.append(f"  {name} {{")
        for col in table.get("columns", [])[:12]:  # cap at 12 cols for readability
            col_name  = _safe(col.get("name","col"))
            col_type  = re.sub(r'[^A-Za-z0-9]','', col.get("data_type","string"))
            col_label = col.get("name","")
            if col.get("is_pk"):
                lines.append(f'    {col_type} {col_name} PK "{col_label}"')
            elif col.get("is_fk") or col.get("is_nk"):
                lines.append(f'    {col_type} {col_name} FK "{col_label}"')
            else:
                lines.append(f'    {col_type} {col_name} "{col_label}"')
        lines.append("  }")

    # ── Relationships ──────────────────────────────────────────────────────
    # Mandatory conformed dimension → fact relationships
    DIM_FK_MAP = {
        "PRODUCT_KEY":    ("DIMPRODUCT",           "classifies"),
        "ORG_KEY":        ("DIMORGANISATION",       "locates"),
        "DATE_KEY":       ("DIMBUSINESSCALENDAR",   "dates"),
        "PRICE_TYPE_KEY": ("DIMRETAILPRICETYPE",    "categorises"),
        "SEASON_KEY":     ("DIMPRODUCTSEASON",      "groups"),
    }

    seen_rels = set()
    for fact in ldm_result.get("fact_tables", []):
        fact_name = _safe(fact.get("table_name",""))
        if not fact_name:
            continue
        for col in fact.get("columns", []):
            col_name = col.get("name","").upper()
            if col_name in DIM_FK_MAP:
                dim_name, label = DIM_FK_MAP[col_name]
                rel_key = (dim_name, fact_name)
                if rel_key not in seen_rels:
                    seen_rels.add(rel_key)
                    lines.append(f'  {dim_name} ||--}}o {fact_name} : "{label}"')

    # Bridge relationships
    for bridge in ldm_result.get("bridge_tables", []):
        bridge_name = _safe(bridge.get("table_name",""))
        if bridge_name:
            lines.append(f'  DIMPRODUCT ||--o{{ {bridge_name} : "has season"')
            lines.append(f'  DIMPRODUCTSEASON ||--o{{ {bridge_name} : "groups items"')

    return "\n".join(lines)


# ── FR coverage matrix ────────────────────────────────────────────────────────

def generate_fr_matrix(ldm_result: dict) -> list[dict]:
    """Build FR coverage matrix — which table satisfies which requirement."""
    matrix = {}

    all_tables = (
        ldm_result.get("dimension_tables", []) +
        ldm_result.get("fact_tables", []) +
        ldm_result.get("bridge_tables", []) +
        ldm_result.get("reference_tables", [])
    )

    for table in all_tables:
        table_name = table.get("table_name","")
        for fr in table.get("fr_references", []):
            if fr not in matrix:
                matrix[fr] = []
            matrix[fr].append(table_name)

    rows = []
    for fr, tables in sorted(matrix.items()):
        rows.append({
            "FR": fr,
            "Tables": ", ".join(tables),
            "Status": "✅ Met",
        })
    return rows


# ── LDM summary ───────────────────────────────────────────────────────────────

def generate_summary(ldm_result: dict) -> list[dict]:
    """Generate table-level summary for display."""
    rows = []
    all_tables = (
        ldm_result.get("dimension_tables", []) +
        ldm_result.get("fact_tables", []) +
        ldm_result.get("bridge_tables", []) +
        ldm_result.get("reference_tables", [])
    )
    for t in all_tables:
        name      = t.get("table_name","")
        ttype     = ("Dimension" if name.startswith("DIM_") else
                     "Fact"      if name.startswith("FACT_") else
                     "Bridge"    if name.startswith("BRIDGE_") else
                     "Reference")
        scd       = f"SCD{t.get('scd_type','')}" if t.get("scd_type") else "—"
        # Use canonical grain from conventions if table's grain is empty
        grain = t.get("grain","") or GRAIN_DECLARATIONS.get(t.get("table_name",""), "")
        grain = grain[:60]
        ncols     = len(t.get("columns",[]))
        source    = t.get("source_system","—")
        fr_refs   = ", ".join(t.get("fr_references",[]))
        rows.append({
            "Table": name,
            "Type": ttype,
            "SCD": scd,
            "Columns": ncols,
            "Source": source,
            "Grain": grain,
            "FR refs": fr_refs,
        })
    return rows


# ── Main entry point ──────────────────────────────────────────────────────────

def build_ldm_output(
    ldm_result: dict,
    output_dir: str = None,
    on_log      = None,
) -> dict:
    # Apply naming conventions (from LDM_NAMING_CONVENTIONS.md)
    enforce_ldm_naming(ldm_result)
    # Ensure all fact tables have mandatory conformed dimension FKs
    enforce_mandatory_fks(ldm_result, on_log=on_log)
    """
    Generate all LDM outputs from the LDM result.

    Returns:
        {
            ddl_ansi:    str   — ANSI SQL DDL
            ddl_sf:      str   — Snowflake DDL
            mermaid:     str   — erDiagram
            fr_matrix:   list  — FR coverage rows
            summary:     list  — table summary rows
            ddl_path:    str   — path to saved DDL file (if output_dir given)
        }
    """
    def log(msg):
        if on_log: on_log(msg)

    log("Generating ANSI SQL DDL…")
    ddl_ansi = generate_ddl(ldm_result, dialect="ansi")

    log("Generating Snowflake DDL…")
    ddl_sf   = generate_ddl(ldm_result, dialect="snowflake")

    log("Generating Mermaid erDiagram…")
    mermaid  = generate_mermaid(ldm_result)

    log("Building FR coverage matrix…")
    fr_matrix = generate_fr_matrix(ldm_result)

    log("Building table summary…")
    summary   = generate_summary(ldm_result)

    log(f"Generated DDL: {ddl_ansi.count('CREATE TABLE')} tables, "
        f"{ddl_ansi.count('CREATE OR REPLACE VIEW')} views")

    # Save DDL to disk if output_dir provided
    ddl_path = None
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)
        ddl_path = os.path.join(output_dir, "LDM_DDL.sql")
        with open(ddl_path, "w", encoding="utf-8") as f:
            f.write(ddl_ansi)
        log(f"DDL saved → {ddl_path}")

    return {
        "ddl_ansi":   ddl_ansi,
        "ddl_sf":     ddl_sf,
        "mermaid":    mermaid,
        "fr_matrix":  fr_matrix,
        "summary":    summary,
        "ddl_path":   ddl_path,
    }
