"""
Step 1b — Slim ontology builder (fast pre-pass).

Purpose: brief the entity extractor (Step 3) before it runs.

Does exactly three things — all fast:
  1. Extracts BRD-specific forbidden patterns (report/dashboard names)
     and expected vocabulary (domain name, key subject areas) via a
     single small LLM call.
  2. Updates SKILL.md with these BRD-specific guardrails so Step 3
     has an accurate forbidden list for this document.
  3. Generates minimal OWL/SHACL stubs (no LLM needed — rule-based).

What it no longer does:
  - No full entity/concept extraction (Step 3 does this better)
  - No large structured JSON output with all concepts
  - No multi-section attribute enumeration

Total LLM calls: 1 (small, fast)
Expected runtime: 5-15 seconds
"""

import sys, os, re, json
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))
from agent.ollama_client import chat, extract_json

GENERATED_DIR = os.path.join(
    os.path.dirname(os.path.dirname(__file__)), "ontology", "generated"
)
SKILL_PATH      = os.path.join(os.path.dirname(os.path.dirname(__file__)), "skills", "SKILL.md")
BASE_SKILL_PATH = os.path.join(os.path.dirname(os.path.dirname(__file__)), "skills", "SKILL_BASE.md")

os.makedirs(GENERATED_DIR, exist_ok=True)

# ── Single fast LLM call ──────────────────────────────────────────────────────

SYSTEM = """You are an experienced subject matter expert in Data Modeling, specifically in Dimensional Modeling and able to precisely design data models Ontology and Graph RAG. Use your knowledge and experience in modeling the DWH schema for CDM and LDM.

You are doing a quick scan of a Business Requirements Document.
Respond ONLY with valid JSON, no explanation, no markdown."""

USER = """Scan this BRD and return a brief JSON with these keys:

"domain_name": short PascalCase business domain name (e.g. "MerchandisingSalesProfit")
"forbidden_names": list of exact report/dashboard/filter names from the BRD that should
  NOT become CDM entities. Include: dashboard names, scorecard names, report names,
  filter names, prompt names (e.g. ["MerchandisingScorecardReport", "MarkdownDashboard",
  "Top10SaleItemsReport", "RegionFilter", "DateRangePrompt"])
"subject_area": one sentence describing what this BRD covers
"filter_to_dimension": list of objects mapping filter/prompt names to their implied
  dimension entity name (e.g. [{{"filter": "RegionFilter", "dimension": "GeographyDimension"}}])

Keep all lists SHORT — only the most important items. Max 10 forbidden_names.

BRD TEXT (first 3000 chars):
---
{brd_text}
---
JSON:"""


# ── SKILL.md updater ──────────────────────────────────────────────────────────

def _update_skill_md(domain: dict) -> None:
    """Append BRD-specific forbidden names and filter mappings to SKILL.md."""
    domain_name   = domain.get("domain_name", "UnknownDomain")
    forbidden     = domain.get("forbidden_names", [])
    filter_to_dim = domain.get("filter_to_dimension", [])
    subject_area  = domain.get("subject_area", "")

    # Read base SKILL.md (without previous BRD-specific section)
    base = ""
    if os.path.exists(BASE_SKILL_PATH):
        with open(BASE_SKILL_PATH, "r", encoding="utf-8") as f:
            base = f.read()
    elif os.path.exists(SKILL_PATH):
        with open(SKILL_PATH, "r", encoding="utf-8") as f:
            content = f.read()
        marker = "\n---\n\n## BRD-SPECIFIC RULES"
        idx = content.find(marker)
        base = content[:idx] if idx != -1 else content
        with open(BASE_SKILL_PATH, "w", encoding="utf-8") as f:
            f.write(base)

    lines = [
        "",
        "---",
        "",
        f"## BRD-SPECIFIC RULES — {domain_name}",
        f"*Auto-generated by Step 1b — {subject_area}*",
        "",
    ]

    if forbidden:
        lines += [
            "### Forbidden entity names for this BRD",
            "These exact names appear in the BRD but must NOT become CDM entities:",
        ]
        for name in forbidden:
            lines.append(f"- `{name}`")
        lines.append("")

    if filter_to_dim:
        lines += [
            "### Filter/Prompt → Dimension mappings (Rule R6)",
            "When these filter/prompt names appear, infer the listed dimension instead:",
        ]
        for m in filter_to_dim:
            f_name = m.get("filter", "")
            d_name = m.get("dimension", "")
            if f_name and d_name:
                lines.append(f"- `{f_name}` → `{d_name}`")
        lines.append("")

    updated = base + "\n".join(lines)
    with open(SKILL_PATH, "w", encoding="utf-8") as f:
        f.write(updated)


# ── Minimal OWL/SHACL stubs (rule-based, no LLM) ─────────────────────────────

def _write_owl_stub(domain_name: str) -> str:
    """Write a minimal OWL ontology stub — no LLM needed."""
    content = f"""@prefix owl:  <http://www.w3.org/2002/07/owl#> .
@prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix cdm:  <https://example.org/cdm/{domain_name}#> .

cdm:{domain_name}Ontology a owl:Ontology ;
    rdfs:label "{domain_name} CDM Ontology" .

cdm:DimensionEntity a owl:Class ; rdfs:label "Dimension Entity" .
cdm:FactEntity      a owl:Class ; rdfs:label "Fact Entity" .
cdm:ReferenceEntity a owl:Class ; rdfs:label "Reference Entity" .
cdm:BridgeEntity    a owl:Class ; rdfs:label "Bridge Entity" .
"""
    path = os.path.join(GENERATED_DIR, f"{domain_name}_ontology.ttl")
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    return path


def _write_shacl_stub(domain_name: str, forbidden_names: list) -> str:
    """Write a minimal SHACL shapes stub with forbidden name constraints."""
    forbidden_constraints = ""
    for name in forbidden_names[:10]:
        forbidden_constraints += f"""
cdm:Forbidden_{name} a sh:NodeShape ;
    sh:targetClass cdm:DimensionEntity, cdm:FactEntity ;
    sh:not [ sh:property [ sh:path cdm:name ; sh:hasValue "{name}" ] ] ;
    sh:message "'{name}' is a forbidden entity name for this BRD" .\n"""

    content = f"""@prefix sh:  <http://www.w3.org/ns/shacl#> .
@prefix cdm: <https://example.org/cdm/{domain_name}#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

cdm:EntityNameShape a sh:NodeShape ;
    sh:targetClass cdm:DimensionEntity, cdm:FactEntity, cdm:ReferenceEntity ;
    sh:property [
        sh:path cdm:name ;
        sh:minCount 1 ;
        sh:pattern "^[A-Z][A-Za-z0-9]*$" ;
        sh:message "Entity name must be PascalCase" ;
    ] .
{forbidden_constraints}"""
    path = os.path.join(GENERATED_DIR, f"{domain_name}_shapes.ttl")
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    return path


# ── Main entry point ──────────────────────────────────────────────────────────

def build_ontology_from_brd(
    brd_text:    str,
    ollama_url:  str,
    model:       str,
    temperature: float = 0.1,
    on_log             = None,
) -> dict:
    """
    Fast ontology pre-pass.
    One small LLM call → SKILL.md update → OWL/SHACL stubs.
    Returns domain dict for pipeline metadata.
    """
    def log(msg):
        if on_log: on_log(msg)

    # Single fast LLM call — first 3000 chars is enough to identify
    # domain, dashboards/report names, and filter patterns
    chunk = brd_text[:3000]
    log("Scanning BRD for domain vocabulary and forbidden patterns…")

    domain = {}
    try:
        raw = chat(
            base_url=ollama_url,
            model=model,
            messages=[
                {"role": "system", "content": SYSTEM},
                {"role": "user",   "content": USER.format(brd_text=chunk)},
            ],
            temperature=temperature,
            format="json",
        )
        domain = extract_json(raw)
        if not isinstance(domain, dict):
            domain = {}
    except Exception as e:
        log(f"LLM scan failed: {e} — using empty domain")
        domain = {}

    domain_name   = domain.get("domain_name", "BusinessDomain")
    forbidden     = domain.get("forbidden_names", [])
    filter_to_dim = domain.get("filter_to_dimension", [])

    log(f"Domain: {domain_name} · {len(forbidden)} forbidden patterns · "
        f"{len(filter_to_dim)} filter→dimension mappings")

    # Update SKILL.md
    log("Updating SKILL.md with BRD-specific guardrails…")
    try:
        _update_skill_md(domain)
        log("SKILL.md updated")
    except Exception as e:
        log(f"SKILL.md update warning: {e}")

    # Write OWL/SHACL stubs
    log("Writing OWL ontology and SHACL shapes stubs…")
    owl_path   = _write_owl_stub(domain_name)
    shacl_path = _write_shacl_stub(domain_name, forbidden)
    log(f"OWL → {os.path.basename(owl_path)}")
    log(f"SHACL → {os.path.basename(shacl_path)}")

    # Save domain JSON
    domain_json_path = os.path.join(GENERATED_DIR, f"{domain_name}_domain.json")
    domain["_domain_name"] = domain_name
    domain["_owl_path"]    = owl_path
    domain["_shacl_path"]  = shacl_path
    try:
        with open(domain_json_path, "w", encoding="utf-8") as f:
            json.dump(domain, f, indent=2)
    except Exception:
        pass

    return domain
